IsraelBlock/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IsraelBlock.Models
{
    public class Supplier
    {
        public long SupplierId { get; set; }
        [Required]
        public String Name { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
    
}

IsraelBlock/Controllers/SuppliersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IsraelBlock.Contexts;
using IsraelBlock.Models;

namespace IsraelBlock.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly EFContextDbContext _context = new EFContextDbContext();

        // GET: Fabricantes
        public ActionResult Index()
        {
            return View(_context.Suppliers.OrderBy(s => s.Name));
        }

        #region Create

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            _context.Suppliers.Add(supplier);
            _context.SaveChanges();
            return RedirectToAction("index");
        }

        #endregion Create

        #region Edit

        public ActionResult Edit(long? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var supplier = _context.Suppliers.Find(id.Value);

            if (supplier == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return View(supplier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(supplier).State = EntityState.Modified;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        #endregion Edit

        #region Delete

        public ActionResult Delete(long? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var supplier = _context.Suppliers.Find(id.Value);

            if (supplier == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return View(supplier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                var s = _context.Suppliers.Find(supplier.SupplierId);

                if (supplier == null)
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);

                _context.Suppliers.Remove(s);

                _context.SaveChanges();

                TempData["Message"] = "Fornecedor " + supplier.Name.ToUpper() + " foi removido";

                return RedirectToAction("index");
            }
            return View();
        }

        /**
         public ActionResult Delete(long id)
        {
            var supplier =
                _context
                .Suppliers
                .Find(id);

            _context
                .Suppliers
                .Remove(supplier);

            _context
                .SaveChanges();

            TempData["Message"] = "Fornecedor " + supplier.Name.ToUpper() + " foi removido";

            return RedirectToAction("index");
        }
             */

        #endregion Delete

        #region Details

        public ActionResult Details(long? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var supplier = _context.Suppliers.Find(id.Value);

            if (supplier == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            return View(supplier);
        }

        #endregion Details

        [HttpPost]
        public JsonResult GetDados()
        {
            var resultado = new
            {
                Sup = _context.Suppliers.OrderBy(s => s.Name)
            };
            return Json(resultado);
        }
    }
}

IsraelBlock/Views/Suppliers/Create.cshtml
@model IsraelBlock.Models.Supplier

@{
    ViewBag.Title = "Cadastrar novo Fornecedor";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Supplier</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

IsraelBlock/Views/Suppliers/Delete.cshtml
@model IsraelBlock.Models.Supplier

@{
    ViewBag.Title = "Visualizando detalhes do Fornecedor";
}

<div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Dados do Fornecedor a ser removido
        </div>
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(model => model.Name)<br />
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user">
                        </i>
                    </span>
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new{@class = "form-control", disabled = "disabled"}})
                </div>
            </div>
        </div>
        <div class="panel-footer panel-info">
            <a href="#" class="btn btn-info" data-toggle="modal"
               data-target="#deleteConfirmationModal">Remover</a>
                @Html.ActionLink("Retornar para a listagem","Index", null, new{@class ="btn btn-primary"})
           
        </div>
    </div>
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
     role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-ELTEismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão de Fornecedor
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o produto @Model.Name.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Suppliers", FormMethod.Post, new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.SupplierId)
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.SupplierId)
                    @Html.HiddenFor(model => model.Name)
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick="$('#delete-form').submit();">
                    Sim, exclua este fornecedor.
                </button>
                <button type="button" class="btn btn-primary"
                        data-dismiss="modal">
                    Não, não exclua este fornecedor.
                </button>
            </div>
        </div>
    </div>
</div>

IsraelBlock/Views/Suppliers/Details.cshtml
@model IsraelBlock.Models.Supplier

@{
    ViewBag.Title = "Visualizando detalhes do Fornecedor";
}

<div class="panel panel-default">
    <div class="panel-body">
        <div>
            <h4>Supplier</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.SupplierId }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>
@Html.Partial("~/Views/Products/_byCategory.cshtml", Model.Products.ToList());

IsraelBlock/Views/Suppliers/Edit.cshtml
@model IsraelBlock.Models.Supplier

@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Supplier</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SupplierId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

IsraelBlock/Views/Suppliers/Index.cshtml
@model IEnumerable<IsraelBlock.Models.Supplier>

@{
    ViewBag.Title = "Fornecedores";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <p>
            @Html.ActionLink("Criar novo", "Create", null, new { @class = "btn btn-primary" })
        </p>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.SupplierId }) |
                            @Html.ActionLink("Detalhes", "Details", new { id = item.SupplierId }) |
                            @Html.ActionLink("Deletar", "Delete", new { id = item.SupplierId })
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>